### ISSUE TITLE
Stuck at Apple logo

### ISSUE THREAD

**Issue by ItumelengMogase** [ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML#4]
I followed all the steps, however, I am stuck at the Apple logo.

System Manufacturer	LENOVO
System Model	81TD
System Type	x64-based PC
System SKU	LENOVO_MT_81TD_BU_idea_FM_Yoga C740-15IML
Processor	Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz, 1608 Mhz, 6 Core(s), 12 Logical Processor(s)
BIOS Version/Date	LENOVO BNCN39WW, 2020/08/27
SMBIOS Version	3.2
Embedded Controller Version	1.39
BIOS Mode	UEFI
BaseBoard Manufacturer	LENOVO
BaseBoard Product	LNVNB161216
BaseBoard Version	SDK0J40697 WIN
Platform Role	Mobile
Secure Boot State	Off
Installed Physical Memory (RAM)	16,0 GB
Kernel DMA Protection	Off
Virtualisation-based security	Running
Virtualisation-based security required security properties	DMA Protection
Virtualisation-based security available security properties	Base Virtualisation Support, DMA Protection, SMM Security Mitigations 1.0, Mode Based Execution Control
Virtualisation-based security services configured	Hypervisor enforced Code Integrity
Virtualisation-based security services running	Hypervisor enforced Code Integrity
Windows Defender Application Control policy	Enforced
Windows Defender Application Control user mode policy	Off
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by ThrRip** [comment]
Well, I know what you met.

Usually, if we add `-v` in `boot-args`, we can see that 'stuck at Apple logo' is the same as 'stuck at `EB|LOG`'.

Try the following:
* Disable CFG Lock by patching BIOS. See [here](https://zhuanlan.zhihu.com/p/266400995) for more information.
* If you can't or don't want to do like that, change `Kernel -> Quirks -> AppleXcpmCfgLock` to true in `/EFI/OC/config.plist`.
* And if it stuck again, change another USB device and re-download Disk Image, check the MD5 of .dmg file and burn it into the USB device.

Also, because I have changed the DVMT-Preallocated to 64MB by patching BIOS, so I didn't write the framebuffer section in `config.plist`, so you may need to pay more attention to `DeviceProperties -> PciRoot(0x0)/Pci(0x2,0x0)`.

Please star this repo and follow me if this helps you.
